implemented juniper ftp client
happy-travel/komoro pull request #350
Opened 2022-11-03 09:23 UTC by DFSko

2022-11-03 09:24 UTC, DaniyarAskarov approved these changes

2022-11-03 10:31 UTC, suhan3z commented on HappyTravel.Komoro.JuniperChannelManager/Infrastructure/Extensions/ServiceCollectionExtensions.cs
> +            // TODO: add real ftp configuration
Should it be like there on production?

2022-11-03 10:31 UTC, suhan3z commented on HappyTravel.Komoro.JuniperChannelManager/Infrastructure/Options/JuniperFtpOptions.cs
> +public class JuniperFtpOptions
Lack of comments

2022-11-03 10:33 UTC, suhan3z commented on HappyTravel.Komoro.JuniperChannelManager/Services/Updater/JuniperFtpClient.cs
> +        { typeof(JpHotelInvNotifRQ), "JP_HotelInvNotifRQ_[A-Z0-9]+.xml" }
To constants

2022-11-03 10:33 UTC, suhan3z requested changes
According to comments

2022-11-04 06:04 UTC, DFSko commented on HappyTravel.Komoro.JuniperChannelManager/Infrastructure/Options/JuniperFtpOptions.cs
> +public class JuniperFtpOptions
Fixed

2022-11-04 06:14 UTC, DFSko commented on HappyTravel.Komoro.JuniperChannelManager/Infrastructure/Extensions/ServiceCollectionExtensions.cs
> +            // TODO: add real ftp configuration
moved options to vault

2022-11-04 10:06 UTC, DFSko commented on HappyTravel.Komoro.JuniperChannelManager/Services/Updater/JuniperFtpClient.cs
> +        { typeof(JpHotelInvNotifRQ), "JP_HotelInvNotifRQ_[A-Z0-9]+.xml" }
Fixed

2022-11-07 07:15 UTC, suhan3z commented on HappyTravel.Komoro.JuniperChannelManager/Services/Updater/JuniperFtpClient.cs
> +            await _ftpClient.DownloadStream(stream, file.FullName, token: cancellationToken);
If stream somehow stored in internals of _ftpClient, it won't be disposed

2022-11-07 07:15 UTC, suhan3z commented on HappyTravel.Komoro.JuniperChannelManager/Services/Updater/JuniperFtpClient.cs
> +        await _ftpClient.Connect(cancellationToken);
Shouldn't we disconnect?

2022-11-07 07:29 UTC, suhan3z commented on HappyTravel.Komoro.JuniperChannelManager/Services/Updater/JuniperFtpClient.cs
> +            await _ftpClient.DownloadStream(stream, file.FullName, token: cancellationToken);
And if an error will occur, stream won't be disposed too

2022-11-07 07:43 UTC, DFSko commented on HappyTravel.Komoro.JuniperChannelManager/Services/Updater/JuniperFtpClient.cs
> +        await _ftpClient.Connect(cancellationToken);
added disconnecting

2022-11-07 07:47 UTC, DFSko commented on HappyTravel.Komoro.JuniperChannelManager/Services/Updater/JuniperFtpClient.cs
> +            await _ftpClient.DownloadStream(stream, file.FullName, token: cancellationToken);
using compiles as try-finally, added using to ftp client

2022-11-07 07:49 UTC, suhan3z approved these changes

2022-11-07 08:15 UTC, merged