Implement availability date restrictions update
happy-travel/komoro pull request #427
Opened 2022-12-12 06:38 UTC by DFSko

2022-12-12 16:03 UTC, oleg-n-k approved these changes

2022-12-12 18:04 UTC, AlexeyShok commented on HappyTravel.Komoro.JuniperChannelManager/HappyTravel.Komoro.JuniperChannelManager.csproj
> +    <ProjectReference Include="..\HappyTravel.Komoro.Data\HappyTravel.Komoro.Data.csproj" />
I think that the channel manager should not work directly with komoro data. You need to use Api service methods to change the data. Working directly with data from the channel manager greatly complicates code cohesion.

2022-12-12 18:13 UTC, AlexeyShok requested changes

2022-12-12 18:13 UTC, AlexeyShok commented on HappyTravel.Komoro.JuniperChannelManager/HappyTravel.Komoro.JuniperChannelManager.csproj
> +    <ProjectReference Include="..\HappyTravel.Komoro.Data\HappyTravel.Komoro.Data.csproj" />
_

2022-12-12 18:14 UTC, AlexeyShok requested changes

2022-12-12 18:14 UTC, AlexeyShok commented on HappyTravel.Komoro.JuniperChannelManager/HappyTravel.Komoro.JuniperChannelManager.csproj
> +    <ProjectReference Include="..\HappyTravel.Komoro.Data\HappyTravel.Komoro.Data.csproj" />
_

2022-12-13 09:54 UTC, DFSko commented on HappyTravel.Komoro.JuniperChannelManager/HappyTravel.Komoro.JuniperChannelManager.csproj
> +    <ProjectReference Include="..\HappyTravel.Komoro.Data\HappyTravel.Komoro.Data.csproj" />
Fixed

2022-12-15 03:53 UTC, AlexeyShok approved these changes

2022-12-15 03:54 UTC, merged